# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Opal Symes
subtitle: I might write about what I do ... I should probably find out what that is first
description: Hi, I'm a software developer who writes Python, Puppet and PHP during the day; and wrangles Rust at night. I also enjoy cooking, sewing, bad puns, and taking on waaay too many projects. In between all of this I fight battles against my own brain, some of which I win.
keywords:
author: Opal Symes
language: en
timezone: Pacific/Auckland

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: "    "

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus
theme_config:
  colorscheme: classic
  page_width: 56

  tags_overview: true
  posts_overview:
    show_all_posts: false
    post_count: 5
  post:
    show_updated: true

  projects_url: https://github.com/software-opal
  social_links:
    github: https://github.com/software-opal
    twitter: https://twitter.com/software_opal
    mail: mailto:code@opal.codes
  nav:
    Home: /
    Writing: /archives/
  logo:
    enabled: true
    width: 60
    height: 60
    url: /icons/logo.png
  favicon:
    desktop:
      url: /icons/favicon.ico
    android:
      url: /icons/favicon-192x192.png
    apple:
      url: /icons/apple-touch-icon.png
  rss:


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:software-opal/software-opal.github.io.git
  branch: master
